# Copyright 2012 Google Inc. All Rights Reserved.

# Travis CI script
# http://travis-ci.org/#!/benvanik/anvil-build

language: python
python:
  - 2.6
  - 2.7

install: python setup.py -q install

script: python setup.py test
